<#
    .SYNOPSIS
        Builds the single self-contained script the pipeline sends to a VM.

    .DESCRIPTION
        Azure Run Command takes one script and no module feed, so the module,
        the entry point, and the call are concatenated into one file. The VM
        needs no network access, no package source, and no credentials, and
        runs exactly the code in this commit.

        The mode is baked into the generated call rather than passed as a
        parameter, so the bundle behaves identically however it is invoked.

    .PARAMETER Mode
        Audit, Remediate, or WhatIf.

    .EXAMPLE
        ./scripts/Build-Bundle.ps1 -Mode Remediate -OutputPath out/remediate.ps1
#>
[CmdletBinding()]
param(
    [ValidateSet('Audit', 'Remediate', 'WhatIf')]
    [string]$Mode = 'Audit',

    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent

if (-not $OutputPath) {
    $OutputPath = Join-Path -Path $root -ChildPath 'out' -AdditionalChildPath ("baseline-{0}.ps1" -f $Mode.ToLower())
}

$module = Get-Content (Join-Path -Path $root -ChildPath 'module' -AdditionalChildPath 'WindowsBaseline', 'WindowsBaseline.psm1') -Raw
$entry = Get-Content (Join-Path -Path $root -ChildPath 'scripts' -AdditionalChildPath 'Invoke-Baseline.ps1') -Raw

# Export-ModuleMember is only valid inside a module; in a plain script it throws.
$module = $module -replace '(?m)^Export-ModuleMember.*$', '# (Export-ModuleMember removed: this bundle is a script, not a module)'

$bundle = @"
# Generated by scripts/Build-Bundle.ps1 -Mode $Mode - do not edit.
# Contents: the WindowsBaseline module, the entry point, and the call.

$module

$entry

Invoke-Baseline -Mode '$Mode'
"@

New-Item -ItemType Directory -Force -Path (Split-Path $OutputPath -Parent) | Out-Null
Set-Content -Path $OutputPath -Value $bundle -Encoding UTF8

# A bundle that does not parse is worse than no bundle: it would fail on the
# VM, where the error is far more expensive to read.
$errors = $null
[System.Management.Automation.Language.Parser]::ParseFile((Resolve-Path $OutputPath), [ref]$null, [ref]$errors) | Out-Null
if ($errors) {
    $errors | ForEach-Object { Write-Error $_.Message }
    throw "Generated bundle does not parse: $OutputPath"
}

Write-Output "Wrote $OutputPath ($([math]::Round((Get-Item $OutputPath).Length / 1KB, 1)) KB, mode $Mode)"
